package generate

import (
	"fmt"
	"runtime/debug"
	"strings"

	"github.com/becheran/smock/internal/logger"
	"github.com/becheran/smock/internal/model"
)

func GenerateMock(res model.InterfaceResult) (mock []byte, err error) {
	logger.Printf("Start generating mock")

	if err := res.ValidateReadyForGenerate(); err != nil {
		return nil, err
	}

	hasTypes := len(res.Types) > 0

	mockedStructName := fmt.Sprintf("%s%s", model.MockPrefix, res.Name)
	mockedStructWithTypeIdentifier := fmt.Sprintf("%s%s", mockedStructName, res.Types.ListIdentifier())
	whenStructName := mockedStructName + "When"
	whenStructNameWithTypeIdentifier := fmt.Sprintf("%s%s", whenStructName, res.Types.ListIdentifier())
	w := newWriter()

	version := "unknown"
	if info, found := debug.ReadBuildInfo(); found {
		version = info.Main.Version
	}
	w.P("// DO NOT EDIT")
	w.P("// Code generated by smock %s", version)
	w.P("")

	w.P("package %s%s", res.PackageName, model.MockPackageSuffix)
	w.P("")

	w.P("import (")
	w.Ident()
	fmtAlreadyImported := false
	for _, i := range res.Imports {
		if hasTypes && i.ImportName() == res.PackageName {
			continue
		}
		if i.ImportName() == "fmt" {
			fmtAlreadyImported = true
		}
		w.P("%s", i)
	}
	if !fmtAlreadyImported {
		w.P(`"fmt"`)
	}
	w.EndIdent()
	w.P(")")
	w.P("")

	// Do not validate when generics are used.
	// It is complicated to retrieve a valid type and assert that one concrete type implements the interface.
	if !hasTypes {
		w.P("// %s must implement interface %s.%s", mockedStructName, res.PackageName, res.Name)
		w.P("var _ %s.%s = &%s{}", res.PackageName, res.Name, mockedStructName)
		w.P("")
	}

	w.P(`func New%s%s(t interface {
	Fatalf(format string, args ...interface{})
	Helper()
}) *%s {`,
		mockedStructName, res.Types.ListTypesWithIdentifiers(), mockedStructWithTypeIdentifier)
	w.Ident()
	w.P("return &%s%s{t: t}", mockedStructName, res.Types.ListIdentifier())
	w.EndIdent()
	w.P("}")
	w.P("")

	w.P("type %s%s struct {", mockedStructName, res.Types.ListTypesWithIdentifiers())
	w.Ident()

	w.P(`t interface {
		Fatalf(format string, args ...interface{})
		Helper()
	}`)
	w.P("")

	for _, m := range res.Methods {
		w.P("v%s []*struct{fun func%s; validateArgs func(%s) bool}", m.Name, m.Signature(), m.Params.IdentWithTypeString(model.IdentTypeInput))
	}
	w.EndIdent()
	w.P("}")
	w.P("")

	for _, f := range res.Methods {
		w.P("func (m *%s) %s%s {", mockedStructWithTypeIdentifier, f.Name, f.Signature())
		w.Ident()
		w.P("for _, check := range m.v%s {", f.Name)
		w.Ident()
		w.P("if check.validateArgs == nil || check.validateArgs(%s) {", f.Params.IdentString(model.IdentTypeInput, true))
		w.Ident()
		if len(f.Results) > 0 {
			w.P("return check.fun(%s)", f.Params.IdentString(model.IdentTypeInput, true))
		} else {
			w.P("check.fun(%s)", f.Params.IdentString(model.IdentTypeInput, true))
			w.P("return")
		}
		w.EndIdent()
		w.P("}")
		w.EndIdent()
		w.P("}")

		args := `fmt.Sprintf("")`
		if len(f.Params) > 0 {
			format := strings.Repeat("%+v, ", len(f.Params))
			format = format[:len(format)-2]
			args = fmt.Sprintf(`fmt.Sprintf("%s", %s)`, format, f.Params.IdentString(model.IdentTypeInput, false))
		}
		w.P(`m.unexpectedCall("%s", %s)`, f.Name, args)
		w.P(`return`)
		w.EndIdent()
		w.P("}")
		w.P("")
	}

	w.P("func (m *%s) WHEN() *%s {", mockedStructWithTypeIdentifier, whenStructNameWithTypeIdentifier)
	w.Ident()
	w.P("return &%s{", whenStructNameWithTypeIdentifier)
	w.Ident()
	w.P("m: m,")
	w.EndIdent()
	w.P("}")
	w.EndIdent()
	w.P("}")
	w.P("")

	w.P("func (m *%s) unexpectedCall(method, args string) {", mockedStructWithTypeIdentifier)
	w.Ident()
	w.P("m.t.Helper()")
	w.P("m.t.Fatalf(`Unexpected call to %s.%%s(%%s)`, method, args)", mockedStructName)
	w.EndIdent()
	w.P("}")
	w.P("")

	w.P("type %s%s struct {", whenStructName, res.Types.ListTypesWithIdentifiers())
	w.Ident()
	w.P("m *%s", mockedStructWithTypeIdentifier)
	w.EndIdent()
	w.P("}")
	w.P("")

	for idx, f := range res.Methods {
		whenArgsStruct := fmt.Sprintf("%s%sArgs", mockedStructName, f.Name)
		whenArgsStructRef := fmt.Sprintf("%s%s", whenArgsStruct, res.Types.ListIdentifier())
		whenNoArgsStruct := fmt.Sprintf("%sEval", whenArgsStruct)
		whenNoArgsStructRef := fmt.Sprintf("%s%s", whenNoArgsStruct, res.Types.ListIdentifier())

		hasParams := len(f.Params) > 0
		hasReturnValues := len(f.Results) > 0

		ref := whenNoArgsStructRef
		if hasParams {
			ref = whenArgsStructRef
		}
		w.P("func (mh *%s) %s() *%s {", whenStructNameWithTypeIdentifier, f.Name, ref)
		w.Ident()

		w.P("var validator struct {")
		w.Ident()
		w.P("fun func%s", f.Signature())
		w.P("validateArgs func(%s) bool", f.Params.IdentWithTypeString(model.IdentTypeInput))
		w.EndIdent()
		w.P("}")
		w.P("validator.fun = func%s { return }", f.Signature())
		w.P("mh.m.v%s = append(mh.m.v%s, &validator)", f.Name, f.Name)
		if hasParams {
			w.P("return &%s {", whenArgsStructRef)
			w.Ident()
			w.P("%s: %s{fun: &validator.fun},", whenNoArgsStruct, whenNoArgsStructRef)
			w.P("validateArgs: &validator.validateArgs,")
		} else {
			w.P("return &%s {", whenNoArgsStructRef)
			w.Ident()
		}
		w.P("fun: &validator.fun,")
		w.EndIdent()
		w.P("}")
		w.EndIdent()
		w.P("}")
		w.P("")

		if hasParams {
			w.P("type %s%s struct {", whenArgsStruct, res.Types.ListTypesWithIdentifiers())
			w.Ident()
			w.P("%s", whenNoArgsStructRef)
			w.P("fun *func%s", f.Signature())
			w.P("validateArgs *func(%s) bool", f.Params.IdentWithTypeString(model.IdentTypeInput))
			w.EndIdent()
			w.P("}")
			w.P("")

			args := ""
			for idx, arg := range f.Params {
				name := arg.Name
				if name == "" {
					name = fmt.Sprintf("_%d", idx)
				}
				args += fmt.Sprintf("match%s interface{Match(%s) bool}", name, arg.Type)
				if idx+1 < len(f.Params) {
					args += ", "
				}
			}
			w.P("func (f *%s) ExpectArgs(%s) *%s {", whenArgsStructRef, args, whenNoArgsStructRef)
			w.Ident()
			w.P("*f.validateArgs = func(%s) bool {", f.Params.IdentWithTypeString(model.IdentTypeInput))
			w.Ident()
			matchString := ""
			for idx, arg := range f.Params {
				name := arg.Name
				input := arg.Name
				if name == "" {
					name = fmt.Sprintf("_%d", idx)
					input = fmt.Sprintf("i%d", idx)
				}
				if strings.HasPrefix(arg.Type, "...") {
					input += "..."
				}
				matchString += fmt.Sprintf("(match%s == nil || match%s.Match(%s))", name, name, input)
				if idx+1 < len(f.Params) {
					matchString += " && "
				}
			}
			w.P("return %s", matchString)
			w.EndIdent()
			w.P("}")
			w.P("return &f.%s", whenNoArgsStruct)
			w.EndIdent()
			w.P("}")
			w.P("")
		}

		w.P("type %s%s struct {", whenNoArgsStruct, res.Types.ListTypesWithIdentifiers())
		w.Ident()
		w.P("fun *func%s", f.Signature())
		w.EndIdent()
		w.P("}")
		w.P("")

		if hasReturnValues {
			w.P("func (f *%s) Return(%s) {", whenNoArgsStructRef, f.Results.IdentWithTypeString(model.IdentTypeResult))
			w.Ident()
			w.P("*f.fun = func%s { return %s }", f.SignatureWithoutIdentifier(), f.Results.IdentString(model.IdentTypeResult, false))
			w.EndIdent()
			w.P("}")
			w.P("")
		}

		w.P("func (f *%s) Do(do func%s) {", whenNoArgsStructRef, f.Signature())
		w.Ident()
		w.P("*f.fun = do")
		w.EndIdent()
		w.P("}")
		if idx < len(res.Methods)-1 {
			w.P("")
		}
	}
	logger.Printf("Finished generating mock")

	return w.buff.Bytes(), nil
}
