// DO NOT EDIT
// Code generated by smock 

package testpackage_mock

import (
	testpackage "github.com/test/testpackage"
	"fmt"
	"reflect"
)

// MockSimple must implement interface testpackage.Simple
var _ testpackage.Simple = &MockSimple{}

func NewMockSimple(t interface {
	Fatalf(format string, args ...interface{})
	Helper()
}) *MockSimple {
	return &MockSimple{t: t}
}

type MockSimple struct {
	t interface {
		Fatalf(format string, args ...interface{})
		Helper()
	}
	
	vFoo []*struct{fun func(); validateArgs func() bool}
	vBar []*struct{fun func(a int, b string) (r0 string); validateArgs func(a int, b string) bool}
	vBaz []*struct{fun func(a string, b string) (r int, r2 int); validateArgs func(a string, b string) bool}
	vFun []*struct{fun func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func()); validateArgs func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) bool}
}

func (m *MockSimple) Foo() {
	for _, check := range m.vFoo {
		if check.validateArgs == nil || check.validateArgs() {
			check.fun()
			return
		}
	}
	m.unexpectedCall("Foo", )
}

func (m *MockSimple) Bar(a int, b string) (r0 string) {
	for _, check := range m.vBar {
		if check.validateArgs == nil || check.validateArgs(a, b) {
			return check.fun(a, b)
		}
	}
	m.unexpectedCall("Bar", a, b)
	return
}

func (m *MockSimple) Baz(a string, b string) (r int, r2 int) {
	for _, check := range m.vBaz {
		if check.validateArgs == nil || check.validateArgs(a, b) {
			return check.fun(a, b)
		}
	}
	m.unexpectedCall("Baz", a, b)
	return
}

func (m *MockSimple) Fun(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func()) {
	for _, check := range m.vFun {
		if check.validateArgs == nil || check.validateArgs(a, b) {
			return check.fun(a, b)
		}
	}
	m.unexpectedCall("Fun", a, b)
	return
}

func (m *MockSimple) unexpectedCall(method string, args ...any) {
	argsStr := ""
	for idx, arg := range args {
		t := reflect.TypeOf(arg)
		if t.Kind() == reflect.Func {
			argsStr += fmt.Sprintf("%T", t)
		} else {
			argsStr += fmt.Sprintf("%+v", t)
		}
		if idx+1 < len(args) {
			argsStr += ", "
		}
	}
	m.t.Helper()
	m.t.Fatalf(`Unexpected call to MockSimple.%s(%s)`, method, argsStr)
}

func (m *MockSimple) WHEN() *MockSimpleWhen {
	return &MockSimpleWhen{
		m: m,
	}
}

type MockSimpleWhen struct {
	m *MockSimple
}

func (mh *MockSimpleWhen) Foo() *MockSimpleFooArgsEval {
	for _, f := range  mh.m.vFoo {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'Foo' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func()
		validateArgs func() bool
	}
	validator.fun = func() { }
	mh.m.vFoo = append(mh.m.vFoo, &validator)
	return &MockSimpleFooArgsEval {
		fun: &validator.fun,
	}
}

type MockSimpleFooArgsEval struct {
	fun *func()
}

func (f *MockSimpleFooArgsEval) Do(do func()) {
	*f.fun = do
}

func (mh *MockSimpleWhen) Bar() *MockSimpleBarArgs {
	for _, f := range  mh.m.vBar {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'Bar' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(a int, b string) (r0 string)
		validateArgs func(a int, b string) bool
	}
	validator.fun = func(a int, b string) (r0 string) { return }
	mh.m.vBar = append(mh.m.vBar, &validator)
	return &MockSimpleBarArgs {
		MockSimpleBarArgsEval: MockSimpleBarArgsEval{fun: &validator.fun},
		validateArgs: &validator.validateArgs,
		fun: &validator.fun,
	}
}

type MockSimpleBarArgs struct {
	MockSimpleBarArgsEval
	fun *func(a int, b string) (r0 string)
	validateArgs *func(a int, b string) bool
}

func (f *MockSimpleBarArgs) ExpectArgs(matcha interface{Match(int) bool}, matchb interface{Match(string) bool}) *MockSimpleBarArgsEval {
	if !(matcha == nil && matchb == nil) {
		*f.validateArgs = func(a int, b string) bool {
			return (matcha == nil || matcha.Match(a)) && (matchb == nil || matchb.Match(b))
		}
	}
	return &f.MockSimpleBarArgsEval
}

type MockSimpleBarArgsEval struct {
	fun *func(a int, b string) (r0 string)
}

func (f *MockSimpleBarArgsEval) Return(r0 string) {
	*f.fun = func(int, string) (string) { return r0 }
}

func (f *MockSimpleBarArgsEval) Do(do func(a int, b string) (r0 string)) {
	*f.fun = do
}

func (mh *MockSimpleWhen) Baz() *MockSimpleBazArgs {
	for _, f := range  mh.m.vBaz {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'Baz' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(a string, b string) (r int, r2 int)
		validateArgs func(a string, b string) bool
	}
	validator.fun = func(a string, b string) (r int, r2 int) { return }
	mh.m.vBaz = append(mh.m.vBaz, &validator)
	return &MockSimpleBazArgs {
		MockSimpleBazArgsEval: MockSimpleBazArgsEval{fun: &validator.fun},
		validateArgs: &validator.validateArgs,
		fun: &validator.fun,
	}
}

type MockSimpleBazArgs struct {
	MockSimpleBazArgsEval
	fun *func(a string, b string) (r int, r2 int)
	validateArgs *func(a string, b string) bool
}

func (f *MockSimpleBazArgs) ExpectArgs(matcha interface{Match(string) bool}, matchb interface{Match(string) bool}) *MockSimpleBazArgsEval {
	if !(matcha == nil && matchb == nil) {
		*f.validateArgs = func(a string, b string) bool {
			return (matcha == nil || matcha.Match(a)) && (matchb == nil || matchb.Match(b))
		}
	}
	return &f.MockSimpleBazArgsEval
}

type MockSimpleBazArgsEval struct {
	fun *func(a string, b string) (r int, r2 int)
}

func (f *MockSimpleBazArgsEval) Return(r int, r2 int) {
	*f.fun = func(string, string) (int, int) { return r, r2 }
}

func (f *MockSimpleBazArgsEval) Do(do func(a string, b string) (r int, r2 int)) {
	*f.fun = do
}

func (mh *MockSimpleWhen) Fun() *MockSimpleFunArgs {
	for _, f := range  mh.m.vFun {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'Fun' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func())
		validateArgs func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) bool
	}
	validator.fun = func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func()) { return }
	mh.m.vFun = append(mh.m.vFun, &validator)
	return &MockSimpleFunArgs {
		MockSimpleFunArgsEval: MockSimpleFunArgsEval{fun: &validator.fun},
		validateArgs: &validator.validateArgs,
		fun: &validator.fun,
	}
}

type MockSimpleFunArgs struct {
	MockSimpleFunArgsEval
	fun *func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func())
	validateArgs *func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) bool
}

func (f *MockSimpleFunArgs) ExpectArgs(matcha interface{Match(func(func(string, string) (int, int), func(string, string) (int, int))) bool}, matchb interface{Match(func(func(string, string) (int, int), func(string, string) (int, int))) bool}) *MockSimpleFunArgsEval {
	if !(matcha == nil && matchb == nil) {
		*f.validateArgs = func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) bool {
			return (matcha == nil || matcha.Match(a)) && (matchb == nil || matchb.Match(b))
		}
	}
	return &f.MockSimpleFunArgsEval
}

type MockSimpleFunArgsEval struct {
	fun *func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func())
}

func (f *MockSimpleFunArgsEval) Return(r func(), r2 func()) {
	*f.fun = func(func(func(string, string) (int, int), func(string, string) (int, int)), func(func(string, string) (int, int), func(string, string) (int, int))) (func(), func()) { return r, r2 }
}

func (f *MockSimpleFunArgsEval) Do(do func(a func(func(string, string) (int, int), func(string, string) (int, int)), b func(func(string, string) (int, int), func(string, string) (int, int))) (r func(), r2 func())) {
	*f.fun = do
}
