// DO NOT EDIT
// Code generated by smock 

package testpackage_mock

import (
	fmt "fmt"
	reflect "reflect"
	sync "sync"
	url "net/url"
)

// NewMockUseUrlWithUrlName creates a new mock object which implements the corresponding interface.
// All function calls can be mocked with a custom behavior for tests using the WHEN function on the mock object.   
func NewMockUseUrlWithUrlName(t interface {
	Fatalf(format string, args ...any)
	Helper()
	Cleanup(f func())
}) *MockUseUrlWithUrlName {
	t.Helper()
	m := &MockUseUrlWithUrlName{t: t}
	t.Cleanup(func () {
		errStr := ""
		for _, v := range m.vInUrl {
			for _, c := range v.expected {
				if c.expectedCalled >= 0 && c.expectedCalled != c.called {
					errStr += fmt.Sprintf("\nExpected 'InUrl' to be called %d times, but was called %d times.", c.expectedCalled, c.called)
				}
			}
		}
		for _, v := range m.vRetUrl {
			for _, c := range v.expected {
				if c.expectedCalled >= 0 && c.expectedCalled != c.called {
					errStr += fmt.Sprintf("\nExpected 'RetUrl' to be called %d times, but was called %d times.", c.expectedCalled, c.called)
				}
			}
		}
		if errStr != "" {
			t.Helper()
			t.Fatalf(errStr)
		}})
	return m
}

type MockUseUrlWithUrlName struct {
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
	
	vInUrl []*struct{validateArgs func(_url url.URL, _fun func(url.URL)) bool; expected []*struct{fun func(_url url.URL, _fun func(url.URL)); expectedCalled int; called int; mutex sync.Mutex}}
	vRetUrl []*struct{validateArgs func() bool; expected []*struct{fun func() (_url url.URL, _fun func(url.URL)); expectedCalled int; called int; mutex sync.Mutex}}
}

func (_this *MockUseUrlWithUrlName) InUrl(_url url.URL, _fun func(url.URL)) {
	for _, _check := range _this.vInUrl {
		if _check.validateArgs == nil || _check.validateArgs(_url, _fun) {
			for _ctr, _exp := range _check.expected {
				_exp.mutex.Lock()
				if _exp.expectedCalled <= 0 || _ctr == len(_check.expected) - 1 || _exp.called < _exp.expectedCalled {
					_exp.called++
					_exp.mutex.Unlock()
					_exp.fun(_url, _fun)
					return
				}
				_exp.mutex.Unlock()
			}
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("InUrl", _url, _fun)
}

func (_this *MockUseUrlWithUrlName) RetUrl() (_url url.URL, _fun func(url.URL)) {
	for _, _check := range _this.vRetUrl {
		if _check.validateArgs == nil || _check.validateArgs() {
			for _ctr, _exp := range _check.expected {
				_exp.mutex.Lock()
				if _exp.expectedCalled <= 0 || _ctr == len(_check.expected) - 1 || _exp.called < _exp.expectedCalled {
					_exp.called++
					_exp.mutex.Unlock()
					return _exp.fun()
				}
				_exp.mutex.Unlock()
			}
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("RetUrl", )
	return
}

func (_this *MockUseUrlWithUrlName) unexpectedCall(method string, args ...any) {
	argsStr := ""
	for idx, arg := range args {
		switch t := reflect.TypeOf(arg); {
		case t.Kind() == reflect.Func:
			argsStr += fmt.Sprintf("%T", t)
		case t.Kind() == reflect.String:
			argsStr += fmt.Sprintf("%q", arg)
		default:
			argsStr += fmt.Sprintf("%+v", arg)
		}
		if idx+1 < len(args) {
			argsStr += ", "
		}
	}
	_this.t.Helper()
	_this.t.Fatalf(`Unexpected call to %s(). If function call is expected add ".WHEN.%s()" to mock.`, method, method)
}

// WHEN is used to set the mock behavior when a specific functions on the object are called.
// Use this to setup your mock for your specific test scenario.
func (_this *MockUseUrlWithUrlName) WHEN() *MockUseUrlWithUrlNameWhen {
	return &MockUseUrlWithUrlNameWhen {
		m: _this,
	}
}

type MockUseUrlWithUrlNameWhen struct {
	m *MockUseUrlWithUrlName
}

// Defines the behavior when InUrl of the mock is called.
//
// As a default the method is expected to be called once.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockUseUrlWithUrlNameWhen) InUrl() *MockUseUrlWithUrlNameInUrlExpectWithTimes {
	for _, f := range _this.m.vInUrl {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'InUrl' is already captured by previous WHEN statement.")
		}
	}
	var defaultExpected struct {
		fun func(_url url.URL, _fun func(url.URL))
		expectedCalled int
		called int
		mutex sync.Mutex
	}
	defaultExpected.fun = func(_url url.URL, _fun func(url.URL)) {}
	defaultExpected.expectedCalled = 1
	
	var validator struct {
		validateArgs func(_url url.URL, _fun func(url.URL)) bool
		expected []*struct {
			fun func(_url url.URL, _fun func(url.URL))
			expectedCalled int
			called int
			mutex sync.Mutex
		}
	}
	validator.expected = append(validator.expected, &defaultExpected)
	_this.m.vInUrl = append(_this.m.vInUrl, &validator)
	var _then func() *MockUseUrlWithUrlNameInUrlWhen
	_then = func() *MockUseUrlWithUrlNameInUrlWhen {
		var _newExpected struct {
			fun func(_url url.URL, _fun func(url.URL))
			expectedCalled int
			called int
			mutex sync.Mutex
		}
		_newExpected.fun = func(_url url.URL, _fun func(url.URL)) { return }
		_newExpected.expectedCalled = 1
		
		validator.expected = append(validator.expected, &_newExpected)
		return &MockUseUrlWithUrlNameInUrlWhen {
			expected: validator.expected,
			then: _then,
			t: _this.m.t,
		}
	}
	
	times := &MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen] {
		expectedCalled: &validator.expected[0].expectedCalled,
		then: _then,
		t: _this.m.t,
		MockUseUrlWithUrlNameThen: MockUseUrlWithUrlNameThen[*MockUseUrlWithUrlNameInUrlWhen]{ then: _then, t: _this.m.t},
	}
	return &MockUseUrlWithUrlNameInUrlExpectWithTimes {
		MockUseUrlWithUrlNameInUrlExpect: &MockUseUrlWithUrlNameInUrlExpect {
			MockUseUrlWithUrlNameInUrlWhen: &MockUseUrlWithUrlNameInUrlWhen {
				expected: validator.expected,
				then: _then,
				t: _this.m.t,
			},
			validateArgs: &validator.validateArgs,
			times: times,
		},
		MockUseUrlWithUrlNameTimes: times,
	}
}

type MockUseUrlWithUrlNameInUrlExpect struct {
	*MockUseUrlWithUrlNameInUrlWhen
	validateArgs *func(_url url.URL, _fun func(url.URL)) bool
	times *MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen]
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *MockUseUrlWithUrlNameInUrlExpect) Expect(_url func(url.URL) bool, _fun func(func(url.URL)) bool) *MockUseUrlWithUrlNameInUrlWhenWithTimes {
	if !(_url == nil && _fun == nil) {
		*_this.validateArgs = func(__url url.URL, __fun func(url.URL)) bool {
			return (_url == nil || _url(__url)) && (_fun == nil || _fun(__fun))
		}
	}
	return &MockUseUrlWithUrlNameInUrlWhenWithTimes {
		MockUseUrlWithUrlNameInUrlWhen: _this.MockUseUrlWithUrlNameInUrlWhen,
		MockUseUrlWithUrlNameTimes: _this.times,
	}
}

type MockUseUrlWithUrlNameInUrlExpectWithTimes struct {
	*MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen]
	*MockUseUrlWithUrlNameInUrlExpect
}

type MockUseUrlWithUrlNameInUrlWhen struct {
	expected []*struct {
		fun func(_url url.URL, _fun func(url.URL))
		expectedCalled int
		called int
		mutex sync.Mutex
	}
	then func() *MockUseUrlWithUrlNameInUrlWhen
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
}

type MockUseUrlWithUrlNameInUrlWhenWithTimes struct {
	*MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen]
	*MockUseUrlWithUrlNameInUrlWhen
}

// Do will execute the provided function and return the result when called
func (_this *MockUseUrlWithUrlNameInUrlWhen) Do(do func(_url url.URL, _fun func(url.URL))) *MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen] {
	_this.expected[len(_this.expected) -1].fun = do
	return &MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameInUrlWhen] {
		expectedCalled: &_this.expected[len(_this.expected) -1].expectedCalled,
		then: _this.then,
		t: _this.t,
		MockUseUrlWithUrlNameThen: MockUseUrlWithUrlNameThen[*MockUseUrlWithUrlNameInUrlWhen]{ then: _this.then, t: _this.t},
	}
}

// Defines the behavior when RetUrl of the mock is called.
//
// As a default the method is expected to be called once.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockUseUrlWithUrlNameWhen) RetUrl() *MockUseUrlWithUrlNameRetUrlWhenWithTimes {
	for _, f := range _this.m.vRetUrl {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'RetUrl' is already captured by previous WHEN statement.")
		}
	}
	var defaultExpected struct {
		fun func() (_url url.URL, _fun func(url.URL))
		expectedCalled int
		called int
		mutex sync.Mutex
	}
	defaultExpected.fun = func() (_url url.URL, _fun func(url.URL)) { return }
	defaultExpected.expectedCalled = 1
	
	var validator struct {
		validateArgs func() bool
		expected []*struct {
			fun func() (_url url.URL, _fun func(url.URL))
			expectedCalled int
			called int
			mutex sync.Mutex
		}
	}
	validator.expected = append(validator.expected, &defaultExpected)
	_this.m.vRetUrl = append(_this.m.vRetUrl, &validator)
	var _then func() *MockUseUrlWithUrlNameRetUrlWhen
	_then = func() *MockUseUrlWithUrlNameRetUrlWhen {
		var _newExpected struct {
			fun func() (_url url.URL, _fun func(url.URL))
			expectedCalled int
			called int
			mutex sync.Mutex
		}
		_newExpected.fun = func() (_url url.URL, _fun func(url.URL)) { return }
		_newExpected.expectedCalled = 1
		
		validator.expected = append(validator.expected, &_newExpected)
		return &MockUseUrlWithUrlNameRetUrlWhen {
			expected: validator.expected,
			then: _then,
			t: _this.m.t,
		}
	}
	
	times := &MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen] {
		expectedCalled: &validator.expected[0].expectedCalled,
		then: _then,
		t: _this.m.t,
		MockUseUrlWithUrlNameThen: MockUseUrlWithUrlNameThen[*MockUseUrlWithUrlNameRetUrlWhen]{ then: _then, t: _this.m.t},
	}
	return &MockUseUrlWithUrlNameRetUrlWhenWithTimes {
		MockUseUrlWithUrlNameRetUrlWhen: &MockUseUrlWithUrlNameRetUrlWhen {
			expected: validator.expected,
			then: _then,
			t: _this.m.t,
		},
		MockUseUrlWithUrlNameTimes: times,
	}
}

type MockUseUrlWithUrlNameRetUrlWhen struct {
	expected []*struct {
		fun func() (_url url.URL, _fun func(url.URL))
		expectedCalled int
		called int
		mutex sync.Mutex
	}
	then func() *MockUseUrlWithUrlNameRetUrlWhen
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
}

type MockUseUrlWithUrlNameRetUrlWhenWithTimes struct {
	*MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen]
	*MockUseUrlWithUrlNameRetUrlWhen
}

// Return the provided values when called
func (_this *MockUseUrlWithUrlNameRetUrlWhen) Return(_url url.URL, _fun func(url.URL)) *MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen] {
	_this.expected[len(_this.expected) -1].fun = func() (url.URL, func(url.URL)) { return _url, _fun }
	return &MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen] {
		expectedCalled: &_this.expected[len(_this.expected) -1].expectedCalled,
		then: _this.then,
		t: _this.t,
		MockUseUrlWithUrlNameThen: MockUseUrlWithUrlNameThen[*MockUseUrlWithUrlNameRetUrlWhen]{ then: _this.then, t: _this.t},
	}
}

// Do will execute the provided function and return the result when called
func (_this *MockUseUrlWithUrlNameRetUrlWhen) Do(do func() (_url url.URL, _fun func(url.URL))) *MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen] {
	_this.expected[len(_this.expected) -1].fun = do
	return &MockUseUrlWithUrlNameTimes[*MockUseUrlWithUrlNameRetUrlWhen] {
		expectedCalled: &_this.expected[len(_this.expected) -1].expectedCalled,
		then: _this.then,
		t: _this.t,
		MockUseUrlWithUrlNameThen: MockUseUrlWithUrlNameThen[*MockUseUrlWithUrlNameRetUrlWhen]{ then: _this.then, t: _this.t},
	}
}

type MockUseUrlWithUrlNameThen [T any] struct {
	then func() T
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
}

// Then continue with another action
func (_this *MockUseUrlWithUrlNameThen[T]) Then() T {
	_this.t.Helper()
	return _this.then()
}

type MockUseUrlWithUrlNameTimes[T any] struct {
	expectedCalled *int
	then func() T
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
	MockUseUrlWithUrlNameThen[T]
}

// Times sets how often the mocked function is expected to be called.
// Test will fail if the number of calls do not match with the expected calls value.
func (_this *MockUseUrlWithUrlNameTimes[T]) Times(times int) *MockUseUrlWithUrlNameThen[T] {
	_this.t.Helper()
	*_this.expectedCalled = times
	retVal := &MockUseUrlWithUrlNameThen[T] { t: _this.t, then: _this.then }
	if times <= 0 {
		retVal.then = func() T {
			_this.t.Helper()
			callString := "AnyTimes"
			if *_this.expectedCalled == 0 { callString = "Never" }
			_this.t.Fatalf("Then statement is not reachable. Expected calls of previous statement: %s", callString)
			panic("Unreachable!")
		}
	}
	return retVal
}

// AnyTimes disables the check how often a function was called.
func (_this *MockUseUrlWithUrlNameTimes[T]) AnyTimes() {
	*_this.expectedCalled = -1
}

// Never will fail if the function is ever called.
func (_this *MockUseUrlWithUrlNameTimes[T]) Never() {
	*_this.expectedCalled = 0
}

