// DO NOT EDIT
// Code generated by smock 

package testpackage_mock

import (
	io "io"
	os "os"
	testpackage "github.com/test/testpackage"
	"fmt"
	"reflect"
)

// MockInheritOwn must implement interface testpackage.InheritOwn
var _ testpackage.InheritOwn = &MockInheritOwn{}

func NewMockInheritOwn(t interface {
	Fatalf(format string, args ...interface{})
	Helper()
}) *MockInheritOwn {
	return &MockInheritOwn{t: t}
}

type MockInheritOwn struct {
	t interface {
		Fatalf(format string, args ...interface{})
		Helper()
	}
	
	vRetType []*struct{fun func() (r0 testpackage.MyType); validateArgs func() bool}
	vUseStdType []*struct{fun func(fi os.FileInfo) (r0 io.Reader); validateArgs func(fi os.FileInfo) bool}
}

func (m *MockInheritOwn) RetType() (r0 testpackage.MyType) {
	for _, check := range m.vRetType {
		if check.validateArgs == nil || check.validateArgs() {
			return check.fun()
		}
	}
	m.unexpectedCall("RetType", )
	return
}

func (m *MockInheritOwn) UseStdType(fi os.FileInfo) (r0 io.Reader) {
	for _, check := range m.vUseStdType {
		if check.validateArgs == nil || check.validateArgs(fi) {
			return check.fun(fi)
		}
	}
	m.unexpectedCall("UseStdType", fi)
	return
}

func (m *MockInheritOwn) unexpectedCall(method string, args ...any) {
	argsStr := ""
	for idx, arg := range args {
		t := reflect.TypeOf(arg)
		if t.Kind() == reflect.Func {
			argsStr += fmt.Sprintf("%T", t)
		} else {
			argsStr += fmt.Sprintf("%+v", t)
		}
		if idx+1 < len(args) {
			argsStr += ", "
		}
	}
	m.t.Helper()
	m.t.Fatalf(`Unexpected call to MockInheritOwn.%s(%s)`, method, argsStr)
}

func (m *MockInheritOwn) WHEN() *MockInheritOwnWhen {
	return &MockInheritOwnWhen{
		m: m,
	}
}

type MockInheritOwnWhen struct {
	m *MockInheritOwn
}

func (mh *MockInheritOwnWhen) RetType() *MockInheritOwnRetTypeArgsEval {
	for _, f := range  mh.m.vRetType {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'RetType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func() (r0 testpackage.MyType)
		validateArgs func() bool
	}
	validator.fun = func() (r0 testpackage.MyType) { return }
	mh.m.vRetType = append(mh.m.vRetType, &validator)
	return &MockInheritOwnRetTypeArgsEval {
		fun: &validator.fun,
	}
}

type MockInheritOwnRetTypeArgsEval struct {
	fun *func() (r0 testpackage.MyType)
}

func (f *MockInheritOwnRetTypeArgsEval) Return(r0 testpackage.MyType) {
	*f.fun = func() (testpackage.MyType) { return r0 }
}

func (f *MockInheritOwnRetTypeArgsEval) Do(do func() (r0 testpackage.MyType)) {
	*f.fun = do
}

func (mh *MockInheritOwnWhen) UseStdType() *MockInheritOwnUseStdTypeArgs {
	for _, f := range  mh.m.vUseStdType {
		if f.validateArgs == nil {
			mh.m.t.Helper()
			mh.m.t.Fatalf("Unreachable condition. Call to 'UseStdType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(fi os.FileInfo) (r0 io.Reader)
		validateArgs func(fi os.FileInfo) bool
	}
	validator.fun = func(fi os.FileInfo) (r0 io.Reader) { return }
	mh.m.vUseStdType = append(mh.m.vUseStdType, &validator)
	return &MockInheritOwnUseStdTypeArgs {
		MockInheritOwnUseStdTypeArgsEval: MockInheritOwnUseStdTypeArgsEval{fun: &validator.fun},
		validateArgs: &validator.validateArgs,
		fun: &validator.fun,
	}
}

type MockInheritOwnUseStdTypeArgs struct {
	MockInheritOwnUseStdTypeArgsEval
	fun *func(fi os.FileInfo) (r0 io.Reader)
	validateArgs *func(fi os.FileInfo) bool
}

func (f *MockInheritOwnUseStdTypeArgs) Expect(fi func(os.FileInfo) bool) *MockInheritOwnUseStdTypeArgsEval {
	if !(fi == nil) {
		*f.validateArgs = func(matchfi os.FileInfo) bool {
			return (fi == nil || fi(matchfi))
		}
	}
	return &f.MockInheritOwnUseStdTypeArgsEval
}

type MockInheritOwnUseStdTypeArgsEval struct {
	fun *func(fi os.FileInfo) (r0 io.Reader)
}

func (f *MockInheritOwnUseStdTypeArgsEval) Return(r0 io.Reader) {
	*f.fun = func(os.FileInfo) (io.Reader) { return r0 }
}

func (f *MockInheritOwnUseStdTypeArgsEval) Do(do func(fi os.FileInfo) (r0 io.Reader)) {
	*f.fun = do
}
