// DO NOT EDIT
// Code generated by smock 

package testpackage_mock

import (
	fmt "fmt"
	io "io"
	os "os"
	reflect "reflect"
	testpackage "github.com/test/testpackage"
)

// MockInheritMultiple must implement interface testpackage.InheritMultiple
var _ testpackage.InheritMultiple = &MockInheritMultiple{}

// NewMockInheritMultiple creates a new mock object which implements the corresponding interface.
// All function calls can be mocked with a custom behavior for tests using the WHEN function on the mock object.   
func NewMockInheritMultiple(t interface {
	Fatalf(format string, args ...any)
	Helper()
	Cleanup(f func())
}) *MockInheritMultiple {
	t.Helper()
	m := &MockInheritMultiple{t: t}
	t.Cleanup(func () {
		errStr := ""
		for _, v := range m.vOwn {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'Own' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vRetType {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'RetType' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vUseStdType {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'UseStdType' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vClose {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'Close' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vRead {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'Read' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vSeek {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'Seek' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		if errStr != "" {
			t.Helper()
			t.Fatalf(errStr)
		}
	})
	return m
}

type MockInheritMultiple struct {
	t interface {
		Fatalf(format string, args ...any)
		Helper()
	}
	
	vOwn []*struct{fun func(i0 int, i1 string) (r0 int, r1 string); validateArgs func(i0 int, i1 string) bool; expectedCalled int; called int}
	vRetType []*struct{fun func() (r0 testpackage.MyType); validateArgs func() bool; expectedCalled int; called int}
	vUseStdType []*struct{fun func(fi os.FileInfo) (r0 io.Reader); validateArgs func(fi os.FileInfo) bool; expectedCalled int; called int}
	vClose []*struct{fun func() (r0 error); validateArgs func() bool; expectedCalled int; called int}
	vRead []*struct{fun func(p []byte) (n int, err error); validateArgs func(p []byte) bool; expectedCalled int; called int}
	vSeek []*struct{fun func(offset int64, whence int) (r0 int64, r1 error); validateArgs func(offset int64, whence int) bool; expectedCalled int; called int}
}

func (_this *MockInheritMultiple) Own(i0 int, i1 string) (r0 int, r1 string) {
	for _, _check := range _this.vOwn {
		if _check.validateArgs == nil || _check.validateArgs(i0, i1) {
			_check.called++
			return _check.fun(i0, i1)
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("Own", i0, i1)
	return
}

func (_this *MockInheritMultiple) RetType() (r0 testpackage.MyType) {
	for _, _check := range _this.vRetType {
		if _check.validateArgs == nil || _check.validateArgs() {
			_check.called++
			return _check.fun()
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("RetType", )
	return
}

func (_this *MockInheritMultiple) UseStdType(fi os.FileInfo) (r0 io.Reader) {
	for _, _check := range _this.vUseStdType {
		if _check.validateArgs == nil || _check.validateArgs(fi) {
			_check.called++
			return _check.fun(fi)
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("UseStdType", fi)
	return
}

func (_this *MockInheritMultiple) Close() (r0 error) {
	for _, _check := range _this.vClose {
		if _check.validateArgs == nil || _check.validateArgs() {
			_check.called++
			return _check.fun()
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("Close", )
	return
}

func (_this *MockInheritMultiple) Read(p []byte) (n int, err error) {
	for _, _check := range _this.vRead {
		if _check.validateArgs == nil || _check.validateArgs(p) {
			_check.called++
			return _check.fun(p)
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("Read", p)
	return
}

func (_this *MockInheritMultiple) Seek(offset int64, whence int) (r0 int64, r1 error) {
	for _, _check := range _this.vSeek {
		if _check.validateArgs == nil || _check.validateArgs(offset, whence) {
			_check.called++
			return _check.fun(offset, whence)
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("Seek", offset, whence)
	return
}

func (_this *MockInheritMultiple) unexpectedCall(method string, args ...any) {
	argsStr := ""
	for idx, arg := range args {
		switch t := reflect.TypeOf(arg); {
		case t.Kind() == reflect.Func:
			argsStr += fmt.Sprintf("%T", t)
		case t.Kind() == reflect.String:
			argsStr += fmt.Sprintf("%q", arg)
		default:
			argsStr += fmt.Sprintf("%+v", arg)
		}
		if idx+1 < len(args) {
			argsStr += ", "
		}
	}
	_this.t.Helper()
	_this.t.Fatalf(`Unexpected call to %s(). If function call is expected add ".WHEN.%s()" to mock.`, method, method)
}

// WHEN is used to set the mock behavior when a specific functions on the object are called.
// Use this to setup your mock for your specific test scenario.
func (_this *MockInheritMultiple) WHEN() *MockInheritMultipleWhen {
	return &MockInheritMultipleWhen{
		m: _this,
	}
}

type MockInheritMultipleWhen struct {
	m *MockInheritMultiple
}

// Defines the behavior when Own of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) Own() *MockInheritMultipleOwnExpect {
	for _, f := range _this.m.vOwn {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'Own' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(i0 int, i1 string) (r0 int, r1 string)
		validateArgs func(i0 int, i1 string) bool
		expectedCalled int
		called int
	}
	validator.fun = func(i0 int, i1 string) (r0 int, r1 string) { return }
	validator.expectedCalled = -1
	_this.m.vOwn = append(_this.m.vOwn, &validator)
	return &MockInheritMultipleOwnExpect {
		MockInheritMultipleOwnWhen: &MockInheritMultipleOwnWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}},
		validateArgs: &validator.validateArgs,
	}
}

type MockInheritMultipleOwnExpect struct {
	*MockInheritMultipleOwnWhen
	validateArgs *func(i0 int, i1 string) bool
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *MockInheritMultipleOwnExpect) Expect(_0 func(int) bool, _1 func(string) bool) *MockInheritMultipleOwnWhen {
	if !(_0 == nil && _1 == nil) {
		*_this.validateArgs = func(_i0 int, _i1 string) bool {
			return (_0 == nil || _0(_i0)) && (_1 == nil || _1(_i1))
		}
	}
	return _this.MockInheritMultipleOwnWhen
}

type MockInheritMultipleOwnWhen struct {
	*MockInheritMultipleTimes
	fun *func(i0 int, i1 string) (r0 int, r1 string)
}

// Return the provided values when called
func (_this *MockInheritMultipleOwnWhen) Return(r0 int, r1 string) *MockInheritMultipleTimes {
	*_this.fun = func(int, string) (int, string) { return r0, r1 }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleOwnWhen) Do(do func(i0 int, i1 string) (r0 int, r1 string)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

// Defines the behavior when RetType of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) RetType() *MockInheritMultipleRetTypeWhen {
	for _, f := range _this.m.vRetType {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'RetType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func() (r0 testpackage.MyType)
		validateArgs func() bool
		expectedCalled int
		called int
	}
	validator.fun = func() (r0 testpackage.MyType) { return }
	validator.expectedCalled = -1
	_this.m.vRetType = append(_this.m.vRetType, &validator)
	return &MockInheritMultipleRetTypeWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}} 
}

type MockInheritMultipleRetTypeWhen struct {
	*MockInheritMultipleTimes
	fun *func() (r0 testpackage.MyType)
}

// Return the provided values when called
func (_this *MockInheritMultipleRetTypeWhen) Return(r0 testpackage.MyType) *MockInheritMultipleTimes {
	*_this.fun = func() (testpackage.MyType) { return r0 }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleRetTypeWhen) Do(do func() (r0 testpackage.MyType)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

// Defines the behavior when UseStdType of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) UseStdType() *MockInheritMultipleUseStdTypeExpect {
	for _, f := range _this.m.vUseStdType {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'UseStdType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(fi os.FileInfo) (r0 io.Reader)
		validateArgs func(fi os.FileInfo) bool
		expectedCalled int
		called int
	}
	validator.fun = func(fi os.FileInfo) (r0 io.Reader) { return }
	validator.expectedCalled = -1
	_this.m.vUseStdType = append(_this.m.vUseStdType, &validator)
	return &MockInheritMultipleUseStdTypeExpect {
		MockInheritMultipleUseStdTypeWhen: &MockInheritMultipleUseStdTypeWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}},
		validateArgs: &validator.validateArgs,
	}
}

type MockInheritMultipleUseStdTypeExpect struct {
	*MockInheritMultipleUseStdTypeWhen
	validateArgs *func(fi os.FileInfo) bool
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *MockInheritMultipleUseStdTypeExpect) Expect(fi func(os.FileInfo) bool) *MockInheritMultipleUseStdTypeWhen {
	if !(fi == nil) {
		*_this.validateArgs = func(_fi os.FileInfo) bool {
			return (fi == nil || fi(_fi))
		}
	}
	return _this.MockInheritMultipleUseStdTypeWhen
}

type MockInheritMultipleUseStdTypeWhen struct {
	*MockInheritMultipleTimes
	fun *func(fi os.FileInfo) (r0 io.Reader)
}

// Return the provided values when called
func (_this *MockInheritMultipleUseStdTypeWhen) Return(r0 io.Reader) *MockInheritMultipleTimes {
	*_this.fun = func(os.FileInfo) (io.Reader) { return r0 }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleUseStdTypeWhen) Do(do func(fi os.FileInfo) (r0 io.Reader)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

// Defines the behavior when Close of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) Close() *MockInheritMultipleCloseWhen {
	for _, f := range _this.m.vClose {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'Close' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func() (r0 error)
		validateArgs func() bool
		expectedCalled int
		called int
	}
	validator.fun = func() (r0 error) { return }
	validator.expectedCalled = -1
	_this.m.vClose = append(_this.m.vClose, &validator)
	return &MockInheritMultipleCloseWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}} 
}

type MockInheritMultipleCloseWhen struct {
	*MockInheritMultipleTimes
	fun *func() (r0 error)
}

// Return the provided values when called
func (_this *MockInheritMultipleCloseWhen) Return(r0 error) *MockInheritMultipleTimes {
	*_this.fun = func() (error) { return r0 }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleCloseWhen) Do(do func() (r0 error)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

// Defines the behavior when Read of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) Read() *MockInheritMultipleReadExpect {
	for _, f := range _this.m.vRead {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'Read' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(p []byte) (n int, err error)
		validateArgs func(p []byte) bool
		expectedCalled int
		called int
	}
	validator.fun = func(p []byte) (n int, err error) { return }
	validator.expectedCalled = -1
	_this.m.vRead = append(_this.m.vRead, &validator)
	return &MockInheritMultipleReadExpect {
		MockInheritMultipleReadWhen: &MockInheritMultipleReadWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}},
		validateArgs: &validator.validateArgs,
	}
}

type MockInheritMultipleReadExpect struct {
	*MockInheritMultipleReadWhen
	validateArgs *func(p []byte) bool
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *MockInheritMultipleReadExpect) Expect(p func([]byte) bool) *MockInheritMultipleReadWhen {
	if !(p == nil) {
		*_this.validateArgs = func(_p []byte) bool {
			return (p == nil || p(_p))
		}
	}
	return _this.MockInheritMultipleReadWhen
}

type MockInheritMultipleReadWhen struct {
	*MockInheritMultipleTimes
	fun *func(p []byte) (n int, err error)
}

// Return the provided values when called
func (_this *MockInheritMultipleReadWhen) Return(n int, err error) *MockInheritMultipleTimes {
	*_this.fun = func([]byte) (int, error) { return n, err }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleReadWhen) Do(do func(p []byte) (n int, err error)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

// Defines the behavior when Seek of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *MockInheritMultipleWhen) Seek() *MockInheritMultipleSeekExpect {
	for _, f := range _this.m.vSeek {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'Seek' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(offset int64, whence int) (r0 int64, r1 error)
		validateArgs func(offset int64, whence int) bool
		expectedCalled int
		called int
	}
	validator.fun = func(offset int64, whence int) (r0 int64, r1 error) { return }
	validator.expectedCalled = -1
	_this.m.vSeek = append(_this.m.vSeek, &validator)
	return &MockInheritMultipleSeekExpect {
		MockInheritMultipleSeekWhen: &MockInheritMultipleSeekWhen{fun: &validator.fun, MockInheritMultipleTimes: &MockInheritMultipleTimes{expectedCalled: &validator.expectedCalled}},
		validateArgs: &validator.validateArgs,
	}
}

type MockInheritMultipleSeekExpect struct {
	*MockInheritMultipleSeekWhen
	validateArgs *func(offset int64, whence int) bool
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *MockInheritMultipleSeekExpect) Expect(offset func(int64) bool, whence func(int) bool) *MockInheritMultipleSeekWhen {
	if !(offset == nil && whence == nil) {
		*_this.validateArgs = func(_offset int64, _whence int) bool {
			return (offset == nil || offset(_offset)) && (whence == nil || whence(_whence))
		}
	}
	return _this.MockInheritMultipleSeekWhen
}

type MockInheritMultipleSeekWhen struct {
	*MockInheritMultipleTimes
	fun *func(offset int64, whence int) (r0 int64, r1 error)
}

// Return the provided values when called
func (_this *MockInheritMultipleSeekWhen) Return(r0 int64, r1 error) *MockInheritMultipleTimes {
	*_this.fun = func(int64, int) (int64, error) { return r0, r1 }
	return _this.MockInheritMultipleTimes
}

// Do will execute the provided function and return the result when called
func (_this *MockInheritMultipleSeekWhen) Do(do func(offset int64, whence int) (r0 int64, r1 error)) *MockInheritMultipleTimes {
	*_this.fun = do
	return _this.MockInheritMultipleTimes
}

type MockInheritMultipleTimes struct {
	expectedCalled *int
}

// Times sets how often the mocked function is expected to be called.
// Test will fail if the number of calls do not match with the expected calls value.
//
// A number < 0 means that a function may be called any times which is also the default behavior.
func (_this *MockInheritMultipleTimes) Times(times int) {
	*_this.expectedCalled = times
}

// AnyTimes disables the check how often a function was called.
func (_this *MockInheritMultipleTimes) AnyTimes() {
	*_this.expectedCalled = -1
}

// Never will fail if the function is ever called. Is the same as Times(0).
func (_this *MockInheritMultipleTimes) Never() {
	*_this.expectedCalled = 0
}

// Once will fail if the function is not called once. Is the same as Times(1).
func (_this *MockInheritMultipleTimes) Once() {
	*_this.expectedCalled = 1
}
