// DO NOT EDIT
// Code generated by smock 

package testpackage_mock

import (
	io "io"
	os "os"
	testpackage "github.com/test/testpackage"
	"fmt"
	"reflect"
)

// mockExtend must implement interface testpackage.Extend
var _ testpackage.Extend = &mockExtend{}

// NewMockExtend creates a new mock object which implements the corresponding interface.
// All function calls can be mocked with a custom behavior for tests using the WHEN function on the mock object.   
func NewMockExtend(t interface {
	Fatalf(format string, args ...interface{})
	Helper()
	Cleanup(f func())
}) *mockExtend {
	t.Helper()
	m := &mockExtend{t: t}
	t.Cleanup(func () {
		errStr := ""
		for _, v := range m.vRetType {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'RetType' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		for _, v := range m.vUseStdType {
			if v.expectedCalled >= 0 && v.expectedCalled != v.called {
				errStr += fmt.Sprintf("\nExpected 'UseStdType' to be called %d times, but was called %d times.", v.expectedCalled, v.called)
			}
		}
		if errStr != "" {
			t.Helper()
			t.Fatalf(errStr)
		}
	})
	return m
}

type mockExtend struct {
	t interface {
		Fatalf(format string, args ...interface{})
		Helper()
	}
	
	vRetType []*struct{fun func() (r0 testpackage.MyType); validateArgs func() bool; expectedCalled int; called int}
	vUseStdType []*struct{fun func(fi os.FileInfo) (r0 io.Reader); validateArgs func(fi os.FileInfo) bool; expectedCalled int; called int}
}

func (_this *mockExtend) RetType() (r0 testpackage.MyType) {
	for _, _check := range _this.vRetType {
		if _check.validateArgs == nil || _check.validateArgs() {
			_check.called++
			return _check.fun()
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("RetType", )
	return
}

func (_this *mockExtend) UseStdType(fi os.FileInfo) (r0 io.Reader) {
	for _, _check := range _this.vUseStdType {
		if _check.validateArgs == nil || _check.validateArgs(fi) {
			_check.called++
			return _check.fun(fi)
		}
	}
	_this.t.Helper()
	_this.unexpectedCall("UseStdType", fi)
	return
}

func (_this *mockExtend) unexpectedCall(method string, args ...any) {
	argsStr := ""
	for idx, arg := range args {
		switch t := reflect.TypeOf(arg); {
		case t.Kind() == reflect.Func:
			argsStr += fmt.Sprintf("%T", t)
		case t.Kind() == reflect.String:
			argsStr += fmt.Sprintf("%q", arg)
		default:
			argsStr += fmt.Sprintf("%+v", arg)
		}
		if idx+1 < len(args) {
			argsStr += ", "
		}
	}
	_this.t.Helper()
	_this.t.Fatalf(`Unexpected call %s(%s)`, method, argsStr)
}

// WHEN is used to set the mock behavior when a specific functions on the object are called.
// Use this to setup your mock for your specific test scenario.
func (_this *mockExtend) WHEN() *mockExtendWhen {
	return &mockExtendWhen{
		m: _this,
	}
}

type mockExtendWhen struct {
	m *mockExtend
}

// Defines the behavior when RetType of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *mockExtendWhen) RetType() *mockExtendRetTypeWhen {
	for _, f := range _this.m.vRetType {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'RetType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func() (r0 testpackage.MyType)
		validateArgs func() bool
		expectedCalled int
		called int
	}
	validator.fun = func() (r0 testpackage.MyType) { return }
	validator.expectedCalled = -1
	_this.m.vRetType = append(_this.m.vRetType, &validator)
	return &mockExtendRetTypeWhen{fun: &validator.fun, mockExtendTimes: &mockExtendTimes{expectedCalled: &validator.expectedCalled}} 
}

type mockExtendRetTypeWhen struct {
	*mockExtendTimes
	fun *func() (r0 testpackage.MyType)
}

// Return the provided values when called
func (_this *mockExtendRetTypeWhen) Return(r0 testpackage.MyType) *mockExtendTimes {
	*_this.fun = func() (testpackage.MyType) { return r0 }
	return _this.mockExtendTimes
}

// Do will execute the provided function and return the result when called
func (_this *mockExtendRetTypeWhen) Do(do func() (r0 testpackage.MyType)) *mockExtendTimes {
	*_this.fun = do
	return _this.mockExtendTimes
}

// Defines the behavior when UseStdType of the mock is called.
//
// As a default the method can be called any times.
// To change this behavior use the Times() method to define how often the function shall be called.
func (_this *mockExtendWhen) UseStdType() *mockExtendUseStdTypeExpect {
	for _, f := range _this.m.vUseStdType {
		if f.validateArgs == nil {
			_this.m.t.Helper()
			_this.m.t.Fatalf("Unreachable condition. Call to 'UseStdType' is already captured by previous WHEN statement.")
		}
	}
	var validator struct {
		fun func(fi os.FileInfo) (r0 io.Reader)
		validateArgs func(fi os.FileInfo) bool
		expectedCalled int
		called int
	}
	validator.fun = func(fi os.FileInfo) (r0 io.Reader) { return }
	validator.expectedCalled = -1
	_this.m.vUseStdType = append(_this.m.vUseStdType, &validator)
	return &mockExtendUseStdTypeExpect {
		mockExtendUseStdTypeWhen: &mockExtendUseStdTypeWhen{fun: &validator.fun, mockExtendTimes: &mockExtendTimes{expectedCalled: &validator.expectedCalled}},
		validateArgs: &validator.validateArgs,
	}
}

type mockExtendUseStdTypeExpect struct {
	*mockExtendUseStdTypeWhen
	validateArgs *func(fi os.FileInfo) bool
}

// Expect will filter for given arguments.
// Each argument is matched with a filter function. Only if all arguments match this mocked function will be called.

// Arguments are either evaluated using the function, or ignored and always true if the function is set to nil.
func (_this *mockExtendUseStdTypeExpect) Expect(fi func(os.FileInfo) bool) *mockExtendUseStdTypeWhen {
	if !(fi == nil) {
		*_this.validateArgs = func(_fi os.FileInfo) bool {
			return (fi == nil || fi(_fi))
		}
	}
	return _this.mockExtendUseStdTypeWhen
}

type mockExtendUseStdTypeWhen struct {
	*mockExtendTimes
	fun *func(fi os.FileInfo) (r0 io.Reader)
}

// Return the provided values when called
func (_this *mockExtendUseStdTypeWhen) Return(r0 io.Reader) *mockExtendTimes {
	*_this.fun = func(os.FileInfo) (io.Reader) { return r0 }
	return _this.mockExtendTimes
}

// Do will execute the provided function and return the result when called
func (_this *mockExtendUseStdTypeWhen) Do(do func(fi os.FileInfo) (r0 io.Reader)) *mockExtendTimes {
	*_this.fun = do
	return _this.mockExtendTimes
}

type mockExtendTimes struct {
	expectedCalled *int
}

// Times sets how often the mocked function is expected to be called.
// Test will fail if the number of calls do not match with the expected calls value.
//
// A number < 0 means that a function may be called any times which is also the default behavior.
func (_this *mockExtendTimes) Times(times int) {
	*_this.expectedCalled = times
}

// AnyTimes disables the check how often a function was called.
func (_this *mockExtendTimes) AnyTimes() {
	*_this.expectedCalled = -1
}

// Never will fail if the function is ever called. Is the same as Times(0).
func (_this *mockExtendTimes) Never() {
	*_this.expectedCalled = 0
}

// Once will fail if the function is not called once. Is the same as Times(1).
func (_this *mockExtendTimes) Once() {
	*_this.expectedCalled = 1
}
