name: Go

on:
  push:
    branches: ["main"]
    tags: v*
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@v0.16.2
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
  test-windows:
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test mock
        run: go test -race ./...
      - name: Test generated mocks
        run: |
          cd test/test_package
          go test -race ./...
  test-linux:
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -race ./...
      - name: Test generated mocks
        run: |
          cd test/test_package
          go test -race ./...
  release:
    runs-on: ubuntu-latest
    needs: [test-windows, test-linux, lint]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Test
        run: go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
